//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construct.SensorHosts.SensorHostBase.BrokerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrokerService.ITransponder")]
    public interface ITransponder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransponder/AddObject", ReplyAction="http://tempuri.org/ITransponder/AddObjectResponse")]
        bool AddObject(object data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransponderChannel : Construct.SensorHosts.SensorHostBase.BrokerService.ITransponder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransponderClient : System.ServiceModel.ClientBase<Construct.SensorHosts.SensorHostBase.BrokerService.ITransponder>, Construct.SensorHosts.SensorHostBase.BrokerService.ITransponder {
        
        public TransponderClient() {
        }
        
        public TransponderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransponderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransponderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransponderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddObject(object data) {
            return base.Channel.AddObject(data);
        }
    }
}
