#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Construct.Server.Entities;
using System.Runtime.Serialization;


namespace Construct.Server.Entities.Adapters
{
    [DataContract]
	public partial class Visualizer
	{
		private string names;
        [DataMember]
		public virtual string Name 
		{ 
		    get
		    {
		        return this.names;
		    }
		    set
		    {
		        this.names = value;
		    }
		}
		
		private Guid iDs;
        [DataMember]
        public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iDs;
		    }
		    set
		    {
		        this.iDs = value;
		    }
		}
		
		private string descriptions;
        [DataMember]
        public virtual string Description 
		{ 
		    get
		    {
		        return this.descriptions;
		    }
		    set
		    {
		        this.descriptions = value;
		    }
		}

	    private string layoutString;
	    [DataMember]
	    public virtual string LayoutString
	    {
		    get
		    {
			    return this.layoutString;
		    }
		    set
		    {
			    this.layoutString = value;
		    }
	    }

        public static implicit operator Entities.Adapters.Visualizer(Entities.Visualizer entity)
        {
            return new Visualizer()
            {
                ID = entity.ID,
                Description = entity.Description,
                Name = entity.Name,
				LayoutString = entity.LayoutString
            };
        }
	}
}
 