#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace Construct.Credentials.Model	
{
	public partial class PasswordCredential
	{
		private Guid _userID;
		public virtual Guid UserID 
		{ 
		    get
		    {
		        return this._userID;
		    }
		    set
		    {
		        this._userID = value;
		    }
		}
		
		private string _password;
		public virtual string Password 
		{ 
		    get
		    {
		        return this._password;
		    }
		    set
		    {
		        this._password = value;
		    }
		}
		
		private bool _isCurrent;
		public virtual bool IsCurrent 
		{ 
		    get
		    {
		        return this._isCurrent;
		    }
		    set
		    {
		        this._isCurrent = value;
		    }
		}
		
	}
}
