#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace Construct.Credentials.Model	
{
	public partial class Server
	{
		private string _serverName;
		public virtual string ServerName 
		{ 
		    get
		    {
		        return this._serverName;
		    }
		    set
		    {
		        this._serverName = value;
		    }
		}
		
		private Guid _iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this._iD;
		    }
		    set
		    {
		        this._iD = value;
		    }
		}
		
		private string _connectionString;
		public virtual string ConnectionString 
		{ 
		    get
		    {
		        return this._connectionString;
		    }
		    set
		    {
		        this._connectionString = value;
		    }
		}
		
		private string _rootServiceUri;
		public virtual string RootServiceUri 
		{ 
		    get
		    {
		        return this._rootServiceUri;
		    }
		    set
		    {
		        this._rootServiceUri = value;
		    }
		}
		
	}
}
