#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace Construct.Credentials.Model	
{
	public partial class User
	{
		private string _userName;
		public virtual string UserName 
		{ 
		    get
		    {
		        return this._userName;
		    }
		    set
		    {
		        this._userName = value;
		    }
		}
		
		private string _lastName;
		public virtual string LastName 
		{ 
		    get
		    {
		        return this._lastName;
		    }
		    set
		    {
		        this._lastName = value;
		    }
		}
		
		private Guid _iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this._iD;
		    }
		    set
		    {
		        this._iD = value;
		    }
		}
		
		private string _firstName;
		public virtual string FirstName 
		{ 
		    get
		    {
		        return this._firstName;
		    }
		    set
		    {
		        this._firstName = value;
		    }
		}
		
	}
}
